### ISSUE TITLE
Remove ActiveRecord dependency 

### ISSUE THREAD

**Issue by SauloSilva** [SauloSilva/sinatra-active-model-serializers#22]
I think about remove ActiveRecord dependency and add ActiveModel with depedency.
ActiveModel is totally adaptable and work to many ORMs (AR, Mongoid, Sequel).

I did [this change](https://github.com/SauloSilva/sinatra-active-model-serializers/compare/feature/active_model?expand=1) and I need a suggestion about this.

/cc @adrianotadao @mateusg

**Comment by mateusg** [comment]
👏

**Comment by adrianotadao** [comment]
I quite agree with you if we aren't using anything in nowhere that ActiveRecord provides to us. 

Anyway, it's a good change.

**Comment by SauloSilva** [comment]
Thanks guys

I will working in this changes and soon I open the PR.

**Comment by SauloSilva** [comment]
@adrianotadao I think about this new version to reference changes.
You agree with 1.0.0 or 0.3.0 for this new version?

**Comment by adrianotadao** [comment]
@SauloSilva I don't have entirely sure but, I guess that the option that more fit in this case, is 0.3.0 ... It's no a big change ... For the user, it still works because ActiveRecord has into your dependencies the ActiveModel ... Look at this: https://github.com/rails/rails/blob/master/activerecord/activerecord.gemspec#L25

**Comment by SauloSilva** [comment]
@adrianotadao make sense.
I agree, we will use 0.3.0, ok?

**Comment by adrianotadao** [comment]
@SauloSilva yeah, go ahead! =D
